// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rule struct {
	Type                 *String  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetType() *String {
	if m != nil {
		return m.Type
	}
	return nil
}

type String struct {
	One                  string   `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two                  string   `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetOne() string {
	if m != nil {
		return m.One
	}
	return ""
}

func (m *String) GetTwo() string {
	if m != nil {
		return m.Two
	}
	return ""
}

var E_Rule = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Rule)(nil),
	Field:         98765,
	Name:          "main.rule",
	Tag:           "bytes,98765,opt,name=rule",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*Rule)(nil), "main.Rule")
	proto.RegisterType((*String)(nil), "main.String")
	proto.RegisterExtension(E_Rule)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x52, 0x48,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27,
	0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0xd4, 0x29, 0x69, 0x70, 0xb1, 0x04, 0x95, 0xe6, 0xa4,
	0x0a, 0x29, 0x70, 0xb1, 0x80, 0xb4, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8, 0x81,
	0xb4, 0xeb, 0x05, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x07, 0x81, 0x65, 0x94, 0x74, 0xb8, 0xd8, 0x20,
	0x7c, 0x21, 0x01, 0x2e, 0xe6, 0xfc, 0x3c, 0x88, 0x52, 0xce, 0x20, 0x10, 0x13, 0x24, 0x52, 0x52,
	0x9e, 0x2f, 0xc1, 0x04, 0x11, 0x29, 0x29, 0xcf, 0xb7, 0xb2, 0xe7, 0x62, 0x29, 0x02, 0x99, 0x2b,
	0xab, 0x07, 0x71, 0x82, 0x1e, 0xcc, 0x09, 0x7a, 0x6e, 0x99, 0xa9, 0x39, 0x29, 0xfe, 0x05, 0x25,
	0x99, 0xf9, 0x79, 0xc5, 0x12, 0x67, 0x9b, 0xd9, 0xc0, 0x16, 0x72, 0x41, 0x2c, 0x04, 0x39, 0x25,
	0x08, 0xac, 0x31, 0x89, 0x0d, 0xac, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x1f, 0xd2,
	0xac, 0xd6, 0x00, 0x00, 0x00,
}
